baseURL: "https://pedrocardoz0.github.io/"
defaultContentLanguage: pt-br
languageCode: pt-br
title: fusca Labs
theme: PaperMod

googleAnalytics: G-6JP6NB2CJE

outputs:
    home:
        - HTML
        - RSS
        - JSON

languages:
    pt-br:
        languageName: "Português (BR)"
        weight: 1
        menu:
            main:
                - name: home
                  url: /
                  weight: 1
                - name: posts
                  url: archives
                  weight: 5
                - name: tags
                  url: tags/
                  weight: 6
                - name: search
                  url: search/
                  weight: 10

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    author: pedrocardoz0
    defaultTheme: auto

    ShowPostNavLinks: true
    ShowReadingTime: true
    ShowToc: true

    homeInfoParams:
        Title: "undefined 🦀"
        Content: >
            rust | blockchain | web3

    socialIcons:
        - name: github
          url: "https://github.com/pedrocardoz0"

    editPost:
        URL: "https://github.com/pedrocardoz0/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    cover:
        image: "https://i.pinimg.com/564x/31/83/5a/31835ac5c67d8a84a5f40b82547cd029.jpg"
