baseURL: "https://pedrocardoz0.github.io/"
defaultContentLanguage: pt-br
languageCode: pt-br
title: fusca labs
theme: PaperMod
paginate: 5

googleAnalytics: G-6JP6NB2CJE

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

languages:
    pt-br:
        languageName: "Português (BR)"
        weight: 1
        menu:
            main:
                - name: home
                  url: /
                  weight: 1
                - name: posts
                  url: archives
                  weight: 5
                - name: tags
                  url: tags/
                  weight: 6
                - name: search
                  url: search/
                  weight: 10

params:
    env: production
    author: pedrocardoz0
    description: rust | web3 | blockchain
    defaultTheme: auto

    images:
        [
            "https://i.pinimg.com/564x/07/ff/66/07ff66c3c43f09c1b81f11b0b503c5dd.jpg",
        ]

    cover:
        hidden: true
        hiddenInList: true
        hiddenInSingle: true

    ShowPostNavLinks: true
    ShowReadingTime: true
    ShowToc: true
    ShareButtons: ["linkedin"]
    UseHugoToc: true

    hidemeta: false
    hideFooter: true

    homeInfoParams:
        Title: "undefined 🦀"
        Content: >
            rust | blockchain | web3

    socialIcons:
        - name: github
          url: "https://github.com/pedrocardoz0"

    editPost:
        URL: "https://github.com/pedrocardoz0/pedrocardoz0.github.io/tree/main/content"
        Text: "Suggest Changes"
        appendFilePath: true

    assets:
        disableFingerprinting: true
        favicon16x16: "icon-block-16.svg"
        favicon32x32: "icon-block-32.svg"
        safari_pinned_tab: "icon-block-32.svg"
