baseURL: "https://pedrocardoz0.github.io/"
languageCode: pt-br
title: Fusca Labs
theme: PaperMod

googleAnalytics: G-6JP6NB2CJE

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    author: pedrocardoz0
    defaultTheme: auto

    ShowPostNavLinks: true
    ShowReadingTime: true

    homeInfoParams:
        Title: "undefined 🦀"
        Content: >
            rust | blockchain | web3
    socialIcons:
        - name: github
          url: "https://github.com/pedrocardoz0"

    editPost:
        URL: "https://github.com/pedrocardoz0/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link
